import Head from 'next/head'
import Link from 'next/link'
import Image from 'next/image'
import React from 'react'
import { BsFillArrowLeftCircleFill } from 'react-icons/bs'

import Footer from '../../../components/footer/Footer'
import NavBar from '../../../components/nav-bar/NavBar'

import react from '../../../public/assets/skills/react.png'
import redux from '../../../public/assets/skills/redux.png'

const index = () => {
  return (
    <div>
      <Head>
        <title>Contact App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/logo.png" />
      </Head>
      <NavBar />
      <div className={'w-full'}>
        <div className={'w-screen h-[25vh] lg:h-[40vh relative]'}>
          <div className={'absolute top-0 left-0 w-full h-[25vh] lg:h-[40vh] bg-black/50 z-10'}>    
            <div className={'absolute top-[70%] max-w-[1240px] w-full left-[50%] right-[50%] translate-x-[-50%] translate-y-[-50%]'}>
              <Link href={'/projects'}>
                <div className={'text-2xl cursor-pointer w-3 h-3 rounded-full hover:text-[#D4AF37]'}>
                  <BsFillArrowLeftCircleFill />
                </div>
              </Link>
              <h2 className={'text-[#fff] text-center'}>Contact App</h2>
              <div className={'flex justify-center gap-4 mt-5'}>
                <Image src={react} alt={''} width={'30'} height={'15'}/>
                <Image src={redux} alt={''} width={'30'} height={'15'}/>
              </div>
            </div>
          </div>
        </div>
        <div className={'h-10'}></div>
        <div className={'max-w-[1240px mx-auto p-10 pt-20'}>
          <div className={'col-span-4'}>
            <p>Project</p>
            <h3 className={'mt-2'}>Overview</h3>
            <p className={'mt-2'}>
              Contact web application, It's a simple web application where you can Create, 
              Read, Update, and Delete contacts. However, when you refresh the web browser all data will 
              be lost. Its a front-end application where I used React.js and Redux to build the application. 
            </p>
            <div className={'mt-10'}>
              <Link 
                href={'https://github.com/Thabiso-Timzo/react-crud-task'}
                className={'px-6 py-3 text-blue-100 no-underline bg-blue-500 rounded hover:bg-blue-600 hover:underline hover:text-blue-200'}
              >
                Source Code
              </Link>
              <Link 
                href={'https://react-crud-task.vercel.app/'}
                className={'ml-5 px-6 py-3 text-blue-100 no-underline bg-blue-500 rounded hover:bg-blue-600 hover:underline hover:text-blue-200'}
              >
                View project
              </Link>
            </div>
          </div>
        </div>
      </div>
      <Footer />
    </div>
  )
}

export default index