import Head from 'next/head'
import React from 'react'

import Footer from '../../../components/footer/Footer'
import NavBar from '../../../components/nav-bar/NavBar'

const th = () => {
  return (
    <div>
        <Head>
            <title>TH</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/logo.png" />
        </Head>
        <NavBar />
        <Footer />
    </div>
  )
}

export default th