import Head from 'next/head'
import Image from 'next/image'
import React from 'react'
import Link from 'next/link'
import { BsFillArrowLeftCircleFill } from 'react-icons/bs'

import NavBar from '../../../components/nav-bar/NavBar'
import Footer from '../../../components/footer/Footer'
import mongo from '../../../public/assets/skills/mongodb.png'
import express from '../../../public/assets/skills/express.png'
import node from '../../../public/assets/skills/node.png'

const Index = () => {
  return (
    <div>
      <Head>
          <title>Express</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/logo.png" />
      </Head>
      <NavBar />
      <div className={'w-full'}>
        <div className={'w-screen h-[25vh] lg:h-[40vh relative]'}>
          <div className={'absolute top-0 left-0 w-full h-[30vh] lg:h-[40vh] bg-black/50 z-10'}>
            <div className={'absolute top-[70%] max-w-[1240px] w-full left-[50%] right-[50%] translate-x-[-50%] translate-y-[-50%]'}>
              <Link href={'/projects'}>
                <div className={'ml-5 mb-5 text-2xl cursor-pointer w-3 h-3 rounded-full hover:text-[#D4AF37]'}>
                  <BsFillArrowLeftCircleFill />
                </div>
              </Link>
              <h2 className={'text-[#fff] text-center'}>Express store API</h2>
              <div className={'flex justify-center gap-4 mt-5'}>
                <Image src={mongo} alt={''} width={'10'} height={'15'}/>
                <Image src={express} alt={''} width={'20'} height={'15'}/>
                <Image src={node} alt={''} width={'20'} height={'15'}/>
              </div>
            </div>
          </div>
        </div>
        <div className={'h-10'}></div>
        <div className={'max-w-[1240px mx-auto p-10 pt-20'}>
          <div className={'col-span-4'}>
            <p>Project</p>
            <h3 className={'mt-2'}>Overview</h3>
            <p className={'mt-2'}>
            An API for an E-commerce store. 
            E-commerce (electronic commerce) is the buying and selling of goods and services
            </p>
            <div className={'mt-10'}>
              
                  <Link 
                    href={'https://github.com/Thabiso-007/api.express-store'}
                    className={'px-6 py-3 text-blue-100 no-underline bg-blue-500 rounded hover:bg-blue-600 hover:underline hover:text-blue-200'}
                  >
                    Source Code
                  </Link>
                
            </div>
            <div className={'mt-10'}>                
              <Link 
                href={'https://api-express-store-lxba.onrender.com/'}
                className={'px-6 py-3 text-blue-100 no-underline bg-blue-500 rounded hover:bg-blue-600 hover:underline hover:text-blue-200'}
              >
                API URL
              </Link>    
            </div>
          </div>
        </div>
      </div>
      <Footer />
    </div>
  )
}

export default Index