import Head from 'next/head'
import React from 'react'

import NavBar from '../../components/nav-bar/NavBar'
import Footer from '../../components/footer/Footer'

const fyur = () => {
  return (
    <div>
        <Head>
            <title>Fyur</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/logo.png" />
        </Head>
        <NavBar />
        <Footer />
    </div>
  )
}

export default fyur