import Head from 'next/head'
import Link from 'next/link'
import Image from 'next/image'
import React from 'react'
import { BsFillArrowLeftCircleFill } from 'react-icons/bs'

import Footer from '../../../components/footer/Footer'
import NavBar from '../../../components/nav-bar/NavBar'

import flask from '../../../public/assets/skills/flask.png'
import html from '../../../public/assets/skills/html.png'
import css from '../../../public/assets/skills/css.png'
import javascript from '../../../public/assets/skills/javascript.png'
import sqlalchemy from '../../../public/assets/skills/sqlAlchemy.png'
import postgreSQL from '../../../public/assets/skills/postgresql.png'

const Index = () => {
  return (
    <div>
        <Head>
            <title>Fyur Project</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/logo.png" />
        </Head>
        <NavBar />
        <div className={'w-full'}>
        <div className={'w-screen h-[25vh] lg:h-[40vh relative]'}>
          <div className={'absolute top-0 left-0 w-full h-[30vh] lg:h-[40vh] bg-black/50 z-10'}>
            <div className={'absolute top-[70%] max-w-[1240px] w-full left-[50%] right-[50%] translate-x-[-50%] translate-y-[-50%]'}>
              <Link href={'/projects'}>
                <div className={'ml-5 mb-5 text-2xl cursor-pointer w-3 h-3 rounded-full hover:text-[#D4AF37]'}>
                  <BsFillArrowLeftCircleFill />
                </div>
              </Link>
              <h2 className={'text-[#fff] text-center'}>Fyur</h2>
              <div className={'mb-3 flex justify-center gap-4 mt-5'}>
                <Image src={flask} alt={''} width={'20'} height={'15'}/>
                <Image src={html} alt={''} width={'20'} height={'15'}/>
                <Image src={javascript} alt={''} width={'20'} height={'15'}/>
                <Image src={sqlalchemy} alt={''} width={'20'} height={'15'}/>
                <Image src={postgreSQL} alt={''} width={'20'} height={'15'}/>
                <Image src={css} alt={''} width={'20'} height={'15'}/>
              </div>
            </div>
          </div>
        </div>
        <div className={'h-10'}></div>
        <div className={'max-w-[1240px mx-auto p-10 pt-20'}>
          <div className={'col-span-4'}>
            <p>Project</p>
            <h3 className={'mt-2'}>Overview</h3>
            <p className={'mt-2'}>
              A website for booking musical venues and artists called Fyyur makes it 
              easier for venues to find and book local performers for performances. 
              This website enables venue owners to list concerts with artists, list 
              new artists and venues, and discover new artists and venues. 
            </p>
            <div className={'mt-10'}>
              <Link 
                href={'https://github.com/Thabiso-Timzo/fyyur-artist-booking'}
                className={'px-6 py-3 text-blue-100 no-underline bg-blue-500 rounded hover:bg-blue-600 hover:underline hover:text-blue-200'}
              >
                Source Code
              </Link>
            </div>
          </div>
        </div>
      </div>
        <Footer />
    </div>
  )
}

export default Index