import Head from 'next/head'
import Image from 'next/image'
import React from 'react'

import NavBar from '../components/nav-bar/NavBar'
import Footer from '../components/footer/Footer'
import touch from '../public/assets/touch.jpg'

const About = () => {
  return (
    <>
    <Head>
        <title>About</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/logo.png" />
      </Head>
    <NavBar />
    <div className={'h-20'}></div>
    <div className={'w-full md:h-screen p-10 flex items-center py-16'}>
      <div className={'max-w-[1240] m-auto md:grid grid-cols-3 gap-8'}>
        <div className={'col-span-2'}>
          <h1 className={'uppercase text-3xl tracking-widest text-[#D4AF37] text-center'}>About Thabiso Hlatshwayo</h1>
          <h2 className={'py-4 text-center'}>Who I am</h2>
          <p className={'py-2 text-gray-100'}>
            I've been coding for the past nine years. I got my start in grade 11 by utilizing HTML and CSS to create web pages. 
            I'm enthusiastic to learn various technological systems. Working with computers and technology have always interested me. 
            I started studying JavaScript, my first programming language, when I graduated from high school. After six months in tertiary, 
            I integrate JavaScript into HTML for the first time. That's how my passion for programming got its start. 
          </p>
          <p className={'py-2 text-gray-100'}>
            I enrolled at a bootcamp (HyperionDev) after tertiary education to learn how to create software using Java and Python.
            I was immediately drawn to learning more after being captivated by how programming could be. I completed my internships at Addmore Digital, 
            where we built various projects using MERN Stack.
          </p>
        </div>
        <div className={'w-full h-auto shadow-xl shadow-black rounded-xl flex items-center justify-center p-4 hover:scale-105 ease-in duration-300'}>
          <Image 
            className={'rounded-xl'} 
            src={touch} 
            alt="" 
            width={'320'} 
            height={'320'} 
          />
        </div>
      </div>
    </div>
    <Footer />
    </>
  )
}

export default About