import Head from 'next/head'
import Image from 'next/image'
import React from 'react'

import NavBar from '../components/nav-bar/NavBar'
import Footer from '../components/footer/Footer'
import touch from '../public/assets/touch.jpg'

const About = () => {
  return (
    <>
    <Head>
        <title>About</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/logo.png" />
      </Head>
    <NavBar />
    <div className={'h-20'}></div>
    <div className={'w-full md:h-screen p-10 flex items-center py-16'}>
      <div className={'max-w-[1240] m-auto md:grid grid-cols-3 gap-8'}>
        <div className={'col-span-2'}>
          <h1 className={'uppercase text-3xl tracking-widest text-[#D4AF37] text-center'}>About Thabiso Hlatshwayo</h1>
          <h2 className={'py-4 text-center'}>Who I am</h2>
          <p className={'py-2 text-gray-100'}>
            For the last nine years, I've been coding. In grade 11, I started building websites using HTML and CSS. 
            I'm eager to learn about various technology platforms. I've always been interested in technology and 
            working with computers. After high school, I started learning JavaScript, which was my first programming 
            language. I finally incorporate JavaScript into HTML after six months of tertiary education. 
            That's how my enthusiasm for programming began.
          </p>
          <p className={'py-2 text-gray-100'}>
            I enrolled at a bootcamp (HyperionDev) after tertiary education to learn how to create software using Java and Python.
            I was immediately drawn to learning more after being captivated by how programming could be. I completed my internships at Addmore Digital, 
            where we built various projects using MERN Stack.
          </p>
        </div>
        <div className={'w-full h-auto shadow-xl shadow-black rounded-xl flex items-center justify-center p-4 hover:scale-105 ease-in duration-300'}>
          <Image 
            className={'rounded-xl'} 
            src={touch} 
            alt="" 
            width={'320'} 
            height={'320'} 
          />
        </div>
      </div>
    </div>
    <Footer />
    </>
  )
}

export default About