import Head from 'next/head'
import Image from 'next/image'
import React from 'react'

import NavBar from '../components/nav-bar/NavBar'
import Footer from '../components/footer/Footer'
import touch from '../public/assets/touch.jpg'

const About = () => {
  return (
    <>
    <Head>
        <title>About</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/logo.png" />
      </Head>
    <NavBar />
    <div className={'h-20'}></div>
    <div className={'w-full md:h-screen p-10 flex items-center py-16'}>
      <div className={'max-w-[1240] m-auto md:grid grid-cols-3 gap-8'}>
        <div className={'col-span-2'}>
          <h1 className={'uppercase text-3xl tracking-widest text-[#D4AF37] text-center'}>About Thabiso Hlatshwayo</h1>
          <h2 className={'py-4 text-center'}>Who I am</h2>
          <p className={'py-2 text-gray-100'}>
            I have been coding for the past nine years. 
            In 11th grade, I began creating websites with HTML and CSS. 
            I am excited to learn about different technology platforms. 
            I have always had a fascination with technology and working with computers. 
            After high school, I began studying JavaScript, my first programming language. 
            After six months of tertiary education, I finally incorporate JavaScript into HTML. 
            That is where my interest in programming began.
          </p>
          <p className={'py-2 text-gray-100'}>
            Following tertiary education, I enrolled in a bootcamp (HyperionDev) to 
            learn how to create software in Java and Python. After being captivated 
            by how powerful programming could be, I was immediately drawn to learning more.
            I finished my internships at Addmore Digital, where we worked on a variety of 
            projects using MERN Stack.
          </p>
        </div>
        <div className={'w-full h-auto shadow-xl shadow-black rounded-xl flex items-center justify-center p-4 hover:scale-105 ease-in duration-300'}>
          <Image 
            className={'rounded-xl'} 
            src={touch} 
            alt="" 
            width={'320'} 
            height={'320'} 
          />
        </div>
      </div>
    </div>
    <Footer />
    </>
  )
}

export default About