import Head from 'next/head'
import React from 'react'
import Footer from '../components/footer/Footer'

import Gude from '../components/gude/Gude'
import NavBar from '../components/nav-bar/NavBar'
import gude from '../public/assets/projects/gude.png'

const projects = () => {
  return (
    <>
    <Head>
        <title>Projects</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/logo.png" />
      </Head>
      <NavBar />
      <div className={'h-20'}></div>
    <div className={'w-full'}>
        <div className={'max-w-[1240] mx-auto px-2 py-16'}>
            <p className={'text-xl tracking-widest uppercase text-[#D4AF37]'}>Projects</p>
            <h2 className={'py-4'}>What I have built</h2>
            <div className={'grid md:grid-cols-2 gap-8'}>
                <Gude title="Gude" backgroundImg={gude} projectURL={'/projects/gude'}/>
            </div>
        </div>
    </div>
    <Footer />
    </>
  )
}

export default projects