import React from 'react'
import Head from 'next/head'

import NavBar from '../components/nav-bar/NavBar'
import HTML from '../components/html/HTML'
import CSS from '../components/css/CSS'
import JavaScript from '../components/javascript/JavaScript'
import Git from '../components/git/Git'
import GitHub from '../components/github/GitHub'
import ReactJS from '../components/react/React'
import NextJS from '../components/next/NextJS'
import Python from '../components/python/Python'
import Redux from '../components/redux/Redux'
import Flask from '../components/flask/Flask'
import NodeJSX from '../components/node/Node'
import ExpressJS from '../components/express/ExpressJS'
import Mongo from '../components/mongo/Mongo'
import MySQL from '../components/mysql/MySQL'
import PostgreSQL from '../components/postgresql/PostgreSQL'
import Tailwind from '../components/tailwind/Tailwind'
import Amazon from '../components/amazon/Amazon'
import Docker from '../components/docker/Docker'
import Footer from '../components/footer/Footer'
import TypeScript from '../components/typescript/TypeScript'
import Django from '../components/django/Django'
import SQLAlchemy from '../components/sqlalchemy/SQLAlchemy'

const Skills = () => {
  return (
    <>
        <Head>
            <title>Skills</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/logo.png" />
        </Head>
        <NavBar />
        <div className={'h-40'}></div>
        <div className={'w-full lg:h-screen p-10 mt-20'}>
            <div className={'max-w-[1240px] flex flex-col justify-center h-full'}>
                <p className={'tracking-widest uppercase text-[#D4AF37] text-xl text-center font-bold'}>Skills</p>
                <h2 className={'py-7 text-center'}>What I can do</h2>
                <div className={'grid md:grid-cols-2 lg:grid-cols-5 gap-8'}>
                    <HTML />
                    <CSS />
                    <JavaScript />
                    <TypeScript />
                    <Git />
                    <GitHub />
                    <ReactJS />
                    <NextJS />
                    <Redux />
                    <Python />
                    <Flask />
                    <Django />
                    <SQLAlchemy />
                    <NodeJSX />
                    <ExpressJS />
                    <Mongo />
                    <MySQL />
                    <PostgreSQL />
                    <Tailwind />
                    <Amazon />
                    <Docker />
                </div>
            </div>
        </div>
        <Footer />
    </>
  )
}

export default Skills